language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
script:
- cd hw_02
- mkdir build
- cmake -H. -Bbuild
- cd build
- cmake --build .
- cmake --build . --target ip_filter_testing
- cmake --build . --target package
deploy:
  provider: bintray
  file: "~/projects_for_home_work/.travis.json"
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  passphrase: $BINTRAY_PASS
