language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
script:
- mkdir dist
- mkdir hw_01/build
- mkdir hw_02/build
- mkdir hw_03/build
- cmake -Hhw_01 -Bhw_01/build
- cmake -Hhw_02 -Bhw_02/build
- cmake -Hhw_03 -Bhw_03/build
- cmake --build hw_01/build
- cmake --build hw_02/build
- cmake --build hw_03/build
- cmake --build hw_01/build --target helloworld_test
- cmake --build hw_02/build --target ip_filter_testing
- cmake --build hw_03/build --target allocator_testing
- cmake --build hw_01/build --target package
- cmake --build hw_02/build --target package
- cmake --build hw_03/build --target package
- cat ../ip.tsv | ./ip_filter > out.tsv
- md5sum out.tsv
- cp *.deb ../
- chmod +x ./.travis_script.sh
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./.travis_script.sh
