language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 gcc-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
script: sh ./.travis_script.sh build
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./.travis_script.sh deploy
