language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
script:
- mkdir dist
- cd ~/hw_01
- mkdir build
- cmake -H. -Bbuild
- cd build
- cmake --build .
- cmake --build . --target helloworld_test
- cmake --build . --target package
- ctest -V
- mv *.deb ~/dist
- cd ~/hw_02
- mkdir build
- cmake -H. -Bbuild
- cd build
- cmake --build .
- cmake --build . --target ip_filter_testing
- cmake --build . --target package
- ctest -V
- cat ../ip.tsv | ./ip_filter > out.tsv
- md5sum out.tsv
- cp *.deb ../
- chmod +x ./.travis_script.sh
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./.travis_script.sh
