notifications:
  email: false

language: cpp

before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 gcc-7 valgrind ltrace graphviz doxygen
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

script: bash ./.travis_script.sh build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: doc/html
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./.travis_script.sh deploy
